name: frontadmin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  shared_preferences: ^2.0.6
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  provider: ^6.0.0
  image_picker: ^0.8.4+4
  fl_chart: ^0.68.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.jpg